=== Ilaiwi/airbyte-connectors/sources/travisci-source/resources/schemas/builds.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "href": {
      "type": "string"
    },
    "id": {
      "type": "number"
    },
    "number": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "duration": {
      "type": "number"
    },
    "event_type": {
      "type": "string"
    },
    "previous_state": {
      "type": [
        "string",
        "null"
      ]
    },
    "pull_request_title": {
      "type": [
        "string",
        "null"
      ]
    },
    "pull_request_number": {
      "type": [
        "string",
        "null"
      ]
    },
    "started_at": {
      "type": "string"
    },
    "finished_at": {
      "type": "string"
    },
    "private": {
      "type": "boolean"
    },
    "priority": {
      "type": "boolean"
    },
    "repository": {
      "type": "object",
      "properties": {
        "slug": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "commit": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "sha": {
          "type": "string"
        },
        "ref": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "compare_url": {
          "type": "string"
        },
        "committed_at": {
          "type": "string"
        }
      }
    },
    "jobs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@type": {
            "type": "string"
          },
          "href": {
            "type": "string"
          },
          "@representation": {
            "type": "string"
          },
          "@permissions": {
            "type": "object",
            "properties": {
              "read": {
                "type": "boolean"
              },
              "restart": {
                "type": "boolean"
              },
              "prioritize": {
                "type": "boolean"
              },
              "debug": {
                "type": "boolean"
              },
              "delete_log": {
                "type": "boolean"
              },
              "cancel": {
                "type": "boolean"
              }
            }
          },
          "id": {
            "type": "number"
          },
          "allow_failure": {
            "type": [
              "string",
              "null"
            ]
          },
          "number": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "started_at": {
            "type": "string"
          },
          "finished_at": {
            "type": "string"
          },
          "build": {
            "type": "object",
            "properties": {
              "href": {
                "type": "string"
              }
            },
            "required": [
              "href"
            ]
          },
          "queue": {
            "type": "string"
          },
          "repository": {
            "type": "object",
            "properties": {
              "href": {
                "type": "string"
              },
              "id": {
                "type": "number"
              },
              "name": {
                "type": "string"
              },
              "slug": {
                "type": "string"
              }
            }
          },
          "commit": {
            "type": "object",
            "properties": {
              "id": {
                "type": "number"
              },
              "sha": {
                "type": "string"
              },
              "ref": {
                "type": "string"
              },
              "message": {
                "type": "string"
              },
              "compare_url": {
                "type": "string"
              },
              "committed_at": {
                "type": "string"
              }
            }
          },
          "owner": {
            "type": "object",
            "properties": {
              "href": {
                "type": "string"
              },
              "id": {
                "type": "number"
              },
              "login": {
                "type": "string"
              },
              "name": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "vcs_type": {
                "type": "string"
              },
              "ro_mode": {
                "type": "boolean"
              }
            }
          },
          "stage": {
            "type": [
              "string",
              "null"
            ]
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          },
          "private": {
            "type": "boolean"
          }
        }
      }
    },
    "created_by": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "login": {
          "type": "string"
        }
      }
    },
    "updated_at": {
      "type": "string"
    }
  }
}

=== Ilaiwi/airbyte-connectors/sources/travisci-source/test_files/builds.json
[
    {
        "id": 249732561,
        "number": "1",
        "state": "failed",
        "started_at": "2022-04-22T08:33:23Z",
        "finished_at": "2022-04-22T08:36:13Z",
        "href": "/build/249732561",
        "jobs": [
            {
                "id": 567902813,
                "created_at": "2022-04-22T08:32:50.699Z",
                "finished_at": "2022-04-22T08:34:01Z",
                "started_at": "2022-04-22T08:33:24Z",
                "state": "failed",
                "href": "/job/567902813"
            },
            {
                "id": 567902814,
                "created_at": "2022-04-22T08:32:50.703Z",
                "finished_at": "2022-04-22T08:36:13Z",
                "started_at": "2022-04-22T08:33:23Z",
                "state": "failed",
                "href": "/job/567902814"
            }
        ],
        "commit": {
            "sha": "531f35363c44f98a9bc7aec11fd198a5e404a475",
            "message": "Create .travis.yml",
            "compare_url": "https://github.com/huongtn/sample-test/compare/ca9a0613a94a...531f35363c44",
            "committed_at": "2022-04-22T08:32:48Z"
        }
    },
    {
        "id": 249732580,
        "number": "2",
        "state": "failed",
        "started_at": "2022-04-25T10:12:37Z",
        "finished_at": "2022-04-25T10:16:58Z",
        "href": "/build/249732580",
        "jobs": [
            {
                "id": 567902862,
                "created_at": "2022-04-22T08:33:11.925Z",
                "finished_at": "2022-04-25T10:13:14Z",
                "started_at": "2022-04-25T10:12:37Z",
                "state": "failed",
                "href": "/job/567902862"
            },
            {
                "id": 567902863,
                "created_at": "2022-04-22T08:33:11.929Z",
                "finished_at": "2022-04-25T10:16:58Z",
                "started_at": "2022-04-25T10:13:49Z",
                "state": "failed",
                "href": "/job/567902863"
            }
        ],
        "commit": {
            "sha": "531f35363c44f98a9bc7aec11fd198a5e404a475",
            "message": "Create .travis.yml",
            "compare_url": "https://github.com/huongtn/sample-test/compare/ca9a0613a94a50c067793296ef48aaa33ceaa8af...531f35363c44f98a9bc7aec11fd198a5e404a475",
            "committed_at": "2022-04-22T08:32:48Z"
        }
    }
]
